const PDFDocument = require("pdfkit");
const fs = require("fs");

// Generate PDF for history export
const generateHistoryPDF = (historyData, userName) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const chunks = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc.fontSize(24).fillColor("#4F46E5").text("SkillSwap - History Report", {
        align: "center",
      });
      doc.moveDown();
      
      doc.fontSize(12).fillColor("#000").text(`User: ${userName}`, {
        align: "left",
      });
      doc.text(`Generated: ${new Date().toLocaleString()}`);
      doc.moveDown();
      doc.moveDown();

      // Sessions
      if (historyData.sessions && historyData.sessions.length > 0) {
        doc.fontSize(18).fillColor("#4F46E5").text("Completed Sessions");
        doc.moveDown(0.5);

        historyData.sessions.forEach((session, index) => {
          doc.fontSize(12).fillColor("#000").text(
            `${index + 1}. ${session.skillName}`
          );
          doc.fontSize(10).fillColor("#666").text(
            `   Date: ${new Date(session.startDate).toLocaleDateString()} - ${new Date(session.endDate).toLocaleDateString()}`
          );
          doc.text(`   Status: ${session.status}`);
          if (session.remarks) {
            doc.text(`   Remarks: ${session.remarks}`);
          }
          doc.moveDown(0.5);
        });
        doc.moveDown();
      }

      // Skill Requests
      if (historyData.requests && historyData.requests.length > 0) {
        doc.fontSize(18).fillColor("#4F46E5").text("Skill Requests");
        doc.moveDown(0.5);

        historyData.requests.forEach((request, index) => {
          doc.fontSize(12).fillColor("#000").text(
            `${index + 1}. ${request.skillName}`
          );
          doc.fontSize(10).fillColor("#666").text(
            `   Status: ${request.status}`
          );
          doc.text(
            `   Date: ${new Date(request.createdAt).toLocaleDateString()}`
          );
          doc.moveDown(0.5);
        });
        doc.moveDown();
      }

      // Points & Badges
      if (historyData.gamification) {
        doc.fontSize(18).fillColor("#4F46E5").text("Gamification");
        doc.moveDown(0.5);
        
        doc.fontSize(12).fillColor("#000").text(
          `Total Points: ${historyData.gamification.points}`
        );
        
        if (historyData.gamification.badges && historyData.gamification.badges.length > 0) {
          doc.text("Badges:");
          historyData.gamification.badges.forEach((badge) => {
            doc.text(`  - ${badge}`);
          });
        }
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(10).fillColor("#999").text(
        "Generated by SkillSwap Application",
        { align: "center" }
      );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateHistoryPDF,
};
