[build]
  command = "cd backend && npm install"
  functions = "backend/netlify"
  publish = "backend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/handler/:splat"
  status = 200
